name: build
on:
  - push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Rust
        run: cargo test --manifest-path="rust/Cargo.toml"
