name: build
on:
  - push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install fpc opam
          opam init --auto-setup
          opam install dune
      - name: "Test: Rust"
        run: cargo test --manifest-path="rust/Cargo.toml"
      - name: "Test: C"
        run: make --directory=c tests
      - name: "Test: OCaml"
        working-directory: ./ocaml
        run: |
          eval $(opam env)
          opam install --yes .
          dune clean
          dune runtest
      - name: "Test: Golang"
        working-directory: ./golang
        run: go test -test.v
      - name: "Test: Pascal"
        working-directory: ./pascal
        run: make tests
